server:
  port: 9090
spring:
  jpa:
    generate-ddl: true
    hibernate.auto-ddl: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/spring_sample
    username: springbootjpa
    password: SpringPassword